#!/bin/sh
# TODO put process in background by SIGINT, and bg upon launch

env () {
    echo $1=$2 >> /etc/bash.bashrc
    echo "export $1=$2" >> /etc/bash.bashrc
    export $1=$2
}

if [ -z ${TWORK_PROF} ]; then env TWORK_PROF $PROF; fi
if [ -z ${TWORK_ALERT} ]; then env TWORK_ALERT $ALERT; fi
if [ -z ${TWORK_BACKUP} ]; then env TWORK_BACKUP $BACKUP; fi
if [ -z ${TWORK_DEVELOP} ]; then env TWORK_DEVELOP $DEVELOP; fi

exec ${HOME}/twork/twork.out
cp --backup=t ${HOME}/twork/twork.db ${TWORK_BACKUP}/
